# Generated by Django 5.0.6 on 2024-06-04 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Scenes', '0003_scenetocase'),
        ('Testproject', '0002_alter_testenv_name_alter_testenv_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='任务名称', max_length=50, verbose_name='任务名称')),
                ('project', models.ForeignKey(help_text='所属项目', on_delete=django.db.models.deletion.PROTECT, to='Testproject.testproject', verbose_name='所属项目')),
                ('scene', models.ManyToManyField(blank=True, help_text='包含的业务流', to='Scenes.testscenes', verbose_name='包含的业务流')),
            ],
            options={
                'verbose_name_plural': '测试任务表',
                'db_table': 'testTask',
            },
        ),
    ]
