# Generated by Django 5.0.6 on 2024-06-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestTask', '0002_testrecord_testreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecord',
            name='create_time',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, help_text='执行时间', verbose_name='执行时间'),
        ),
    ]
