# Generated by Django 5.0.6 on 2024-06-03 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestInterface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='用例名称', max_length=50, verbose_name='用例名称')),
                ('headers', models.JSONField(blank=True, default=dict, help_text='请求头', null=True, verbose_name='请求头配置')),
                ('request', models.JSONField(blank=True, default=dict, help_text='请求参数配置', null=True, verbose_name='请求参数配置')),
                ('file', models.JSONField(blank=True, default=list, help_text='请求上传的文件参数', null=True, verbose_name='请求上传的文件参数')),
                ('setup_script', models.TextField(blank=True, default='', help_text='前置脚本', null=True, verbose_name='前置脚本')),
                ('teardown_script', models.TextField(blank=True, default='', help_text='后置脚本', null=True, verbose_name='后置脚本')),
                ('interface', models.ForeignKey(help_text='接口', on_delete=django.db.models.deletion.CASCADE, to='TestInterface.testinterface', verbose_name='接口')),
            ],
            options={
                'db_table': 'interFaceCases',
            },
        ),
    ]
