# Generated by Django 5.0.6 on 2024-06-03 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testenv',
            name='name',
            field=models.CharField(help_text='测试环境名称', max_length=150, verbose_name='测试环境名称'),
        ),
        migrations.AlterField(
            model_name='testenv',
            name='project',
            field=models.ForeignKey(help_text='所属项目', on_delete=django.db.models.deletion.CASCADE, to='Testproject.testproject', verbose_name='所属项目'),
        ),
    ]
