# Generated by Django 5.0.6 on 2024-06-04 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scenes', '0001_initial'),
        ('Testproject', '0002_alter_testenv_name_alter_testenv_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestScent',
            new_name='TestScenes',
        ),
    ]
