# Generated by Django 5.0.6 on 2024-06-04 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scenes', '0002_rename_testscent_testscenes'),
        ('TestInterface', '0003_rename_intercase_interfacecase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneToCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(blank=True, help_text='执行顺序', null=True, verbose_name='执行顺序')),
                ('icase', models.ForeignKey(help_text='接口用例', on_delete=django.db.models.deletion.PROTECT, to='TestInterface.interfacecase', verbose_name='接口用例')),
                ('scene', models.ForeignKey(help_text='测试业务流', on_delete=django.db.models.deletion.PROTECT, to='Scenes.testscenes', verbose_name='测试业务流')),
            ],
            options={
                'verbose_name_plural': '测试业务流中的执行步骤',
            },
        ),
    ]
