# Generated by Django 5.0.6 on 2024-06-05 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TestInterface', '0003_rename_intercase_interfacecase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='提交时间', verbose_name='提交时间')),
                ('desc', models.CharField(blank=True, help_text='bug描述', max_length=30, verbose_name='bug描述')),
                ('status', models.CharField(help_text='bug状态', max_length=10, verbose_name='bug状态')),
                ('user', models.CharField(blank=True, help_text='提交者', max_length=10, verbose_name='提交者')),
                ('info', models.JSONField(blank=True, default=dict, help_text='用例执行信息', verbose_name='用例执行信息')),
                ('interface', models.ForeignKey(help_text='所属接口', on_delete=django.db.models.deletion.CASCADE, to='TestInterface.testinterface', verbose_name='所属接口')),
            ],
            options={
                'verbose_name_plural': 'bug管理表',
                'db_table': 'bugmanage',
            },
        ),
        migrations.CreateModel(
            name='BugHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('handle', models.TextField(blank=True, help_text='处理操作', verbose_name='处理操作')),
                ('update_user', models.CharField(blank=True, help_text='更新用户', max_length=32, verbose_name='更新用户')),
                ('bug', models.ForeignKey(help_text='bug', on_delete=django.db.models.deletion.CASCADE, to='BugManage.bugmanage', verbose_name='bug')),
            ],
            options={
                'verbose_name_plural': 'bug操作记录表',
                'db_table': 'bughandle',
            },
        ),
    ]
